# Generated by Django 5.1.5 on 2025-02-10 17:34

import bulk_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipientDataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sheet', models.FileField(upload_to=bulk_core.models.bulk_recipient_directory_path)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('wechat', 'WeChat'), ('email', 'Email')], max_length=20)),
            ],
        ),
    ]
