# Generated by Django 5.1.5 on 2025-02-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_core', '0002_alter_recipientcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientdatasheet',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bulk_core.recipientcategory'),
        ),
    ]
