# Generated by Django 5.1.5 on 2025-02-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_core', '0004_alter_recipientdatasheet_category_temprecipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempRecipient',
        ),
    ]
