# Generated by Django 5.1.5 on 2025-02-13 04:41

import bulk_core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_core', '0005_delete_temprecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRecipientDataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sheet', models.FileField(upload_to=bulk_core.models.bulk_recipient_directory_path)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('wechat', 'WeChat'), ('email', 'Email')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_core.recipientcategory')),
            ],
        ),
    ]
