# Generated by Django 5.1.5 on 2025-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecipient',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
