# Generated by Django 5.1.5 on 2025-02-13 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_core', '0005_delete_temprecipient'),
        ('bulk_email', '0002_emailrecipient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_core.recipientcategory')),
                ('data_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_core.recipientdatasheet')),
            ],
        ),
    ]
