# Generated by Django 5.1.5 on 2025-02-13 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_core', '0006_temprecipientdatasheet'),
        ('bulk_email', '0003_temprecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_core.recipientcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='TempRecipient',
        ),
    ]
