# Generated by Django 5.1.5 on 2025-02-13 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0004_tempemailrecipient_delete_temprecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempemailrecipient',
            name='temp_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
