# Generated by Django 5.1.5 on 2025-02-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0005_tempemailrecipient_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempemailrecipient',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
