# Generated by Django 5.1.5 on 2025-02-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0007_remove_emailattachment_sent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bulk_email.emailtemplate'),
        ),
    ]
