# Generated by Django 5.0 on 2025-03-01 12:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0009_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
