# Generated by Django 5.0 on 2025-06-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0011_emailsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'permissions': [('sendmail_emailtemplate', 'Can send email')]},
        ),
        migrations.AlterField(
            model_name='emailsession',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
    ]
