# Generated by Django 5.0 on 2025-06-21 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0012_alter_emailtemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
