# Generated by Django 5.0 on 2025-06-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0013_sentmail_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmail',
            name='created_at',
        ),
    ]
