# Generated by Django 5.0 on 2025-06-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0014_remove_sentmail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmail',
            name='sent_date',
            field=models.DateField(auto_now=True),
        ),
    ]
