# Generated by Django 5.0 on 2026-01-13 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_email', '0015_sentmail_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempemailrecipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
