# Generated by Django 5.0 on 2025-02-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatssappAttachment',
            new_name='WhatsappAttachment',
        ),
    ]
