# Generated by Django 5.0 on 2025-06-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_whatsapp', '0002_rename_whatssappattachment_whatsappattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsapptemplate',
            options={'permissions': [('sendmessage_whatsapptemplate', 'Can send whatsapp messages')]},
        ),
    ]
