# Generated by Django 5.0 on 2025-06-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_whatsapp', '0005_sentmessage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmessage',
            name='created_at',
        ),
    ]
