# Generated by Django 5.0 on 2025-06-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_whatsapp', '0006_remove_sentmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='sent_date',
            field=models.DateField(auto_now=True),
        ),
    ]
