# Generated by Django 5.1.5 on 2025-02-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nationality_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('control_activation', 'Can Active/ Deactivate account')]},
        ),
    ]
