# Generated by Django 5.1.5 on 2025-02-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_activate_deactivate_account', 'Can activate/deactivate accounts'), ('can_view_active_inactive_users', 'Can view only active/inactive users')]},
        ),
    ]
