# Generated by Django 5.1.5 on 2025-02-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_activate_deactivate_account', 'Can activate/deactivate user'), ('can_view_active_inactive_users', 'Can view active/inactive users')]},
        ),
    ]
