# Generated by Django 5.0 on 2025-03-01 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bulk_core', '0006_temprecipientdatasheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempWCRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('recipient_id', models.CharField(max_length=100)),
                ('temp_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_core.recipientcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WeChatRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('recipient_id', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_core.recipientcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WeChatTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delete_status', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='bulk_messages_data/wechat_attachment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bulk_wechat.wechattemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SentWCMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=255)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipient_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_wechat.wechatrecipient')),
                ('message_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulk_wechat.wechattemplate')),
            ],
        ),
    ]
