# Generated by Django 5.0 on 2025-06-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wechattemplate',
            options={'permissions': [('sendmessage_wechattemplate', 'Can send WeChat messages')]},
        ),
    ]
