# Generated by Django 5.0 on 2025-06-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_wechat', '0002_alter_wechattemplate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wechattemplate',
            options={'permissions': [('sendmessage_wechattemplate', 'Can send we chat messages')]},
        ),
    ]
