# Generated by Django 5.0 on 2025-05-11 04:58

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('visiting_address', models.TextField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('concern_fe_rep', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fabric_article_supplier', models.CharField(max_length=255)),
                ('fabric_article_fexpo', models.CharField(max_length=255)),
                ('fabric_mill_supplier', models.CharField(max_length=255)),
                ('rd_generated_date', models.DateField(blank=True, null=True)),
                ('fabric_mill_source', models.CharField(max_length=255)),
                ('coo', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('mill_reference', models.CharField(max_length=255)),
                ('fabricexpo_reference', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('po', models.CharField(max_length=100)),
                ('composition', models.CharField(max_length=255)),
                ('construction', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('cut_width', models.CharField(max_length=50)),
                ('wash', models.CharField(max_length=100)),
                ('price_per_yard', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shrinkage_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock_qty', models.PositiveIntegerField()),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('concern_person', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business_data.contactinfo')),
                ('buyer_name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('is_international', models.BooleanField(default=True)),
                ('payment_term', models.CharField(blank=True, max_length=100)),
                ('fabric_reference', models.CharField(blank=True, max_length=255)),
            ],
            bases=('business_data.contactinfo',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business_data.contactinfo')),
                ('customer_name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('is_local', models.BooleanField(default=True)),
                ('payment_term', models.CharField(blank=True, max_length=100)),
                ('fabric_reference', models.CharField(blank=True, max_length=255)),
            ],
            bases=('business_data.contactinfo',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business_data.contactinfo')),
                ('mill_name', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('concern_person', models.CharField(max_length=255)),
                ('concern_person_designation', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('product_range', models.CharField(max_length=100)),
                ('speciality', models.CharField(blank=True, max_length=255)),
                ('wechat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_term', models.CharField(max_length=100)),
                ('fabric_reference', models.CharField(blank=True, max_length=255)),
            ],
            bases=('business_data.contactinfo',),
        ),
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='business_data.contactinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('is_wechat', models.BooleanField(default=False)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='business_data.contactinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='business_data.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_data.customer'),
        ),
    ]
