# Generated by Django 5.0 on 2025-05-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
