# Generated by Django 5.0 on 2025-05-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0002_contactinfo_date_contactinfo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='category',
            field=models.CharField(blank=True, help_text='Apparel or Textile', max_length=100, null=True),
        ),
    ]
