# Generated by Django 5.0 on 2025-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0003_buyer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personphone',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
