# Generated by Django 5.0 on 2025-05-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0004_alter_personphone_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.CharField(blank=True, help_text='Apparel or Textile', max_length=100, null=True),
        ),
    ]
