# Generated by Django 5.0 on 2025-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0005_customer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
