# Generated by Django 5.0 on 2025-05-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0006_alter_product_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
