# Generated by Django 5.0 on 2025-05-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0007_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
    ]
