# Generated by Django 5.0 on 2025-05-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0009_alter_buyer_is_deleted_alter_customer_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
    ]
