# Generated by Django 5.0 on 2025-05-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0010_alter_buyer_is_deleted_alter_customer_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personemail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
