# Generated by Django 5.0 on 2025-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0011_alter_personemail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='whatsapp_number',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
