# Generated by Django 5.0 on 2025-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0015_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
