# Generated by Django 5.0 on 2025-06-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0018_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
