# Generated by Django 5.0 on 2025-06-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0019_product_weave'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='sample_type',
            field=models.CharField(choices=[('FABRIC', 'Fabric Sample'), ('GARMENT', 'Garment View'), ('MODEL', 'Model View')], default='FABRIC', help_text='Type of sample shown in the image', max_length=20),
        ),
    ]
