# Generated by Django 5.0 on 2025-06-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0020_productimage_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_number',
            field=models.BigIntegerField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
