# Generated by Django 5.0 on 2025-06-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0021_product_barcode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
