# Generated by Django 5.0 on 2025-06-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0023_product_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
